<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<?php $rooms = $block->getRooms(); ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <?php foreach ($rooms as $room): ?>
            <div class="card col-md-4" style="width: 30rem; margin-bottom: 15px;" align="center">
                <img src="<?= $this->getMediaUrl().'catalog/tmp/category/'.$room->getImage(); ?>" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><?= $room->getRoom_name(); ?></h5>
                    <p class="card-text">Sku: <?= $room->getSku(); ?></p>
                    <p class="card-text">Tình trạng: <?php
                        if ($room->getStatus() == 1) {
                            echo "Open";
                        } else{
                            echo "Close";
                        }
                        ?></p>
                    <p class="card-text">Địa chỉ: <?= $room->getAddress(); ?></p>
                    <b><input type="text" value="Giá: <?= number_format($room->getPrice()); ?>" readonly style="margin-bottom: 7px; text-align: center;"></b>
                    <a href="#" class="btn btn-primary">Đặt phòng</a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>