<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="contactinfo">
                <ul class="nav nav-pills">
                    <li><a href="#"><i class="fa fa-phone"></i> <?= $this->getData('store_phone'); ?></a></li>
                    <li><a href="#"><i class="fa fa-envelope"></i> <?= $this->getData('store_email'); ?>></a></li>
                </ul>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="social-icons pull-right">
                <ul class="nav navbar-nav">
                    <li><a href="<?= $this->getData('store_facebook'); ?>"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="<?= $this->getData('store_twitter'); ?>"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>